/**  by zhangruidong   **/
var data = [//存储所有文件夹\文件\图片
    {
        "id":1,
        "name":"微云",
        "pid":0
    },{
        "id":2,
        "name":"JS课程",
        "pid":1
    },{
        "id":3,
        "name":"CSS课程",
        "pid":1
    },{
        "id":4,
        "name":"HTML课程",
        "pid":1
    },{
        "id":5,
        "name":"浮动",
        "pid":3
    },{
        "id":6,
        "name":"定时器",
        "pid":2
    },{
        "id":7,
        "name":"字符串",
        "pid":2
    },{
        "id":8,
        "name":"数组",
        "pid":2
    },{
        "id":9,
        "name":"运动",
        "pid":2
    },{
        "id":10,
        "name":"字符串方法",
        "pid":7
    },{
        "id":11,
        "name":"字符串练习",
        "pid":7
    },{
        "id":12,
        "name":"浮动练习",
        "pid":5
    }
];
